steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1']
- name: 'gcr.io/gcpproject-410115/sonar-scanner:4.6.0.2311'
  args:
  - '-Dsonar.host.url=https://sonarcloud.io'
  - '-Dsonar.login={Tipstat2405@github}'
  - '-Dsonar.projectKey={tipstat2405}'
  - '-Dsonar.organization={Tipstat2405}'
  - '-Dsonar.sources=.'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myrepo', '--image', 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1', '--region', 'us-east1','--allow-unauthenticated']
images:
- 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1'
- 'gcr.io/gcpproject-410115/sonar-scanner:4.6.0.2311'

tags: ['cloud-builders-community']
