steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1']
  args: 
  - 'build'
  - '--build-arg'
  - 'SONARQUBE_SCANNER_CLI_VERSION=4.6.0.2311'
  - '-t'
  - 'us-east1-docker.pkg.dev/gcpproject-410115/sonar-scanner:latest'
  - '-t'
  - 'us-east1-docker.pkg.dev/gcpproject-410115/sonar-scanner:4.6.0.2311'
  - '.'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'myrepo', '--image', 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1', '--region', 'us-east1','--allow-unauthenticated']
images:
- 'us-east1-docker.pkg.dev/gcpproject-410115/myrepo/repo:v1'
- 'us-east1-docker.pkg.dev/gcpproject-410115/sonar-scanner:latest'
- 'us-east1-docker.pkg.dev/gcpproject-410115/sonar-scanner:4.6.0.2311'

tags: ['cloud-builders-community']
